### ISSUE TITLE
IDEs (e.g. PyCharm) don't recognize Metaflow decorators

### ISSUE THREAD

**Issue by tuulos** [Netflix/metaflow#354]
Metaflow decorators are imported at the runtime, so IDEs can't find them based on static analysis. We could find a way to make the setup more IDE-friendly.

Context: https://gitter.im/metaflow_org/community?at=5f8e151898a7774f1b53afc6

**Comment by tuulos** [comment]
@bsridatta there has been some progress on this issue: You can get tooltips now for many Metaflow's public APIs, like `self.next`, `metaflow.S3` etc.

Decorators are a bit of a special case because they are constructed dynamically on the fly, making it harder for IDEs to recognize them. We are still working on to fix that issue

**Comment by bsridatta** [comment]
Got it @tuulos , thanks for the quick reponse! 

Yes its only decorators that are without tool tips. Although for example FlowSpec shows warning like below in VSCode.

```
"FlowSpec" is not exported from module "metaflow"
  Import from "metaflow.flowspec" instead
```

**Comment by romain-intel** [comment]
This should be fixed by #1557

**Comment by solesensei** [comment]
Still have the issue. Any fixes?
![image](https://github.com/Netflix/metaflow/assets/24857057/a592efa1-e350-4175-8a5c-b09df99eab29)

**Comment by solesensei** [comment]
Worked for me
```
pip install metaflow-stubs -U
```
